print("Numele,prenumele: Tambur Ana-Maria")
print("Data,luna,anul nașterii:01.07.2004")
print("Locul nașterii: mun.Bălți, Republica Moldova")
print("Domiciliul: str. 1 Mai 7-A")
print("Numărul de telefon: 061033691")
print("Școala:Instituția Publică Liceul Teoretic Mihai Eminescu, clasa a 10-a")
print("Operare la calculator în aplicațiile: Microsoft Word, Microsoft Excel, Microsoft Power Point, PASCAL, PYTHON")
print("Hobby:mă ocup cu cântatul,desenul")
print("Recomandări, referințe: Zavorotnîi-Eșanu Elena - dirigintă în gimnaziu")
print("Semnatura: TAnaMaria")
print("Data: 15.09.2020")